//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvoiceManager.Properties.ApplicationTexts", typeof(ApplicationTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłączenie 2FA nie zmienia kluczy używanych w aplikacjach uwierzytelniających. Jeśli chcesz zmienić klucz
        ///        używany w aplikacji uwierzytelniającej, powinieneś &lt;a asp-page=&quot;./ResetAuthenticator&quot;&gt;zresetować klucze uwierzytelniające.&lt;/a&gt;.
        /// </summary>
        public static string About2FADisabling {
            get {
                return ResourceManager.GetString("About2FADisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta akcja służy tylko do wyłączenia 2FA..
        /// </summary>
        public static string About2FADisablingTitle {
            get {
                return ResourceManager.GetString("About2FADisablingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta aplikacja została stworzona w celu ułatwienia życia księgowych i przedsiębiorców, których przytłacza ilość wystawianych faktur. Mamy nadzieję, że z nami prowadzenie własnej działalności stanie się dużo przyjemniejsze!.
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O aplikacji.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID księgowego.
        /// </summary>
        public static string AccountantID {
            get {
                return ResourceManager.GetString("AccountantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie kontem.
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj kolejną usługę do logowania..
        /// </summary>
        public static string AddAnotherLoginService {
            get {
                return ResourceManager.GetString("AddAnotherLoginService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@niedzwiedzki.net.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizer faktur.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveOperationName {
            get {
                return ResourceManager.GetString("ApproveOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja aplikacji uwierzytelniającej.
        /// </summary>
        public static string AuthConfiguration {
            get {
                return ResourceManager.GetString("AuthConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to otpauth://totp/{0}:{1}?secret={2}&amp;issuer={0}&amp;digits=6.
        /// </summary>
        public static string AuthenticatorUriFormat {
            get {
                return ResourceManager.GetString("AuthenticatorUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wróć do listy.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można wyłączyć 2FA dla użytkownika o identyfikatorze &apos;{0}&apos;, ponieważ nie jest obecnie włączony..
        /// </summary>
        public static string CannotDisable2FA {
            get {
                return ResourceManager.GetString("CannotDisable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień ustawienia swojego konta.
        /// </summary>
        public static string ChangeYourAccountSettings {
            get {
                return ResourceManager.GetString("ChangeYourAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby zresetować hasło, należy podać kod..
        /// </summary>
        public static string CodeMustBeSuppliedForPasswordResetException {
            get {
                return ResourceManager.GetString("CodeMustBeSuppliedForPasswordResetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź adres e-mail.
        /// </summary>
        public static string ConfirmEmailAdress {
            get {
                return ResourceManager.GetString("ConfirmEmailAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdź proszę swój adres e-mail &lt;a href=&apos;{0}&apos;&gt;klikając tutaj&lt;/a&gt;..
        /// </summary>
        public static string ConfirmEmailAdressByClickingHere {
            get {
                return ResourceManager.GetString("ConfirmEmailAdressByClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konrad Niedźwiedzki&lt;br /&gt;Możesz znaleźć mnie na: &lt;a href=&quot;https://www.linkedin.com/in/konrad-niedzwiedzki/&quot;&gt;LinkedIn&lt;/a&gt;&lt;br /&gt;Mam też swoją stronę internetową: &lt;a href=&quot;http://niedzwiedzki.net/&quot;&gt;niedzwiedzki.net&lt;/a&gt;&lt;br /&gt;.
        /// </summary>
        public static string ContactAdressText {
            get {
                return ResourceManager.GetString("ContactAdressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        public static string ContactTitle {
            get {
                return ResourceManager.GetString("ContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;copy; 2019 - Konrad Niedźwiedzki.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodawanie faktury.
        /// </summary>
        public static string CreateHeader {
            get {
                return ResourceManager.GetString("CreateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nową fakturę.
        /// </summary>
        public static string CreateInvoiceButton {
            get {
                return ResourceManager.GetString("CreateInvoiceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stwórz nowe konto..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateOperationName {
            get {
                return ResourceManager.GetString("CreateOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj fakturę.
        /// </summary>
        public static string CreateTitle {
            get {
                return ResourceManager.GetString("CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuwanie faktury.
        /// </summary>
        public static string DeleteHeader {
            get {
                return ResourceManager.GetString("DeleteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteOperationName {
            get {
                return ResourceManager.GetString("DeleteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jesteś pewien, że chcesz usunąć tę fakturę?.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń fakturę.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Szczegóły faktury.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz uwierzytelnienie dwuskładnikowe (2FA).
        /// </summary>
        public static string Disable2FA {
            get {
                return ResourceManager.GetString("Disable2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyłącz 2FA.
        /// </summary>
        public static string Disable2FAButton {
            get {
                return ResourceManager.GetString("Disable2FAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edycja faktury.
        /// </summary>
        public static string EditTitle {
            get {
                return ResourceManager.GetString("EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobierz aplikację do uwierzytelniania dwuskładnikowego, taką jak Microsoft Authenticator &lt;a href=&quot;https://go.microsoft.com/fwlink/?Linkid=825071&quot;&gt;Windows Phone&lt;/a&gt;, &lt;a href=&quot;https://go.microsoft.com/fwlink/?Linkid=825072&quot;&gt;Android&lt;/a&gt; lub &lt;a href=&quot;https://go.microsoft.com/fwlink/?Linkid=825073&quot;&gt;iOS&lt;/a&gt; albo Google Authenticator dla &lt;a href=&quot;https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&amp;amp;hl=en&quot;&gt;Android&lt;/a&gt; lub &lt;a href=&quot;https://itunes.apple.com/us/app/google-authentica [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EnableAuthStep1 {
            get {
                return ResourceManager.GetString("EnableAuthStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź ten klucz &lt;kbd&gt;{0}&lt;/kbd&gt; do Twojej aplikacji do uwierzytelniania dwuskładnikowego. Wielkość liter i spacje nie mają znaczenia..
        /// </summary>
        public static string EnableAuthStep2 {
            get {
                return ResourceManager.GetString("EnableAuthStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Po wprowadzeniu powyższego klucza, Twoja aplikacja do uwierzytelniania dwuskładnikowego zapewni Ci dostęp z unikalnym kodem. Wprowadź kod w polu potwierdzenia poniżej..
        /// </summary>
        public static string EnableAuthStep3 {
            get {
                return ResourceManager.GetString("EnableAuthStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aby użyć aplikacji uwierzytelniającej, wykonaj następujące kroki:.
        /// </summary>
        public static string EnableAuthSteps {
            get {
                return ResourceManager.GetString("EnableAuthSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string ErrorPageHeader {
            get {
                return ResourceManager.GetString("ErrorPageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        public static string ErrorPageTitle {
            get {
                return ResourceManager.GetString("ErrorPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podczas przetwarzania żądania wystąpił błąd..
        /// </summary>
        public static string ErrorWhenProcessingRequest {
            get {
                return ResourceManager.GetString("ErrorWhenProcessingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while seeding the database..
        /// </summary>
        public static string ErrorWhileSeedingTheDatabase {
            get {
                return ResourceManager.GetString("ErrorWhileSeedingTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login zewnętrzny został dodany..
        /// </summary>
        public static string ExternalLoginAdded {
            get {
                return ResourceManager.GetString("ExternalLoginAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login zewnętrzny został usunięty..
        /// </summary>
        public static string ExternalLoginRemoved {
            get {
                return ResourceManager.GetString("ExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzanie zewnętrznymi loginami.
        /// </summary>
        public static string ExternalLoginsManagament {
            get {
                return ResourceManager.GetString("ExternalLoginsManagament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zewnętrzne loginy.
        /// </summary>
        public static string ExtrernalLogins {
            get {
                return ResourceManager.GetString("ExtrernalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przefiltrowana lista faktur.
        /// </summary>
        public static string FilteredTitle {
            get {
                return ResourceManager.GetString("FilteredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtruj listę po dacie wystawienia.
        /// </summary>
        public static string FilterSubmit {
            get {
                return ResourceManager.GetString("FilterSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generuj kody odzyskiwania.
        /// </summary>
        public static string GenerateCodesButton {
            get {
                return ResourceManager.GetString("GenerateCodesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generowanie kodów odzyskiwania uwierzytelniania dwuskładnikowego (2FA).
        /// </summary>
        public static string GeneratingTwoFactorAuthenticationRecoveryCodes {
            get {
                return ResourceManager.GetString("GeneratingTwoFactorAuthenticationRecoveryCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta akcja generuje nowe kody odzyskiwania..
        /// </summary>
        public static string GeneretingCodesTitle {
            get {
                return ResourceManager.GetString("GeneretingCodesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę firmy do faktury.
        /// </summary>
        public static string InsertNameOfCompanyErrorMessage {
            get {
                return ResourceManager.GetString("InsertNameOfCompanyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktura.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceAccountants.
        /// </summary>
        public static string InvoiceAccountantRole {
            get {
                return ResourceManager.GetString("InvoiceAccountantRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceAdministrators.
        /// </summary>
        public static string InvoiceAdministratorsRole {
            get {
                return ResourceManager.GetString("InvoiceAdministratorsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faktury.
        /// </summary>
        public static string InvoicesIndexTitle {
            get {
                return ResourceManager.GetString("InvoicesIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logowanie.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj używając konta {0}.
        /// </summary>
        public static string LoginWithAccount {
            get {
                return ResourceManager.GetString("LoginWithAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w naszym InvoiceManager! :) Tu będzie kiedyś super zajebista strona tytułowa. :D.
        /// </summary>
        public static string MainPageText {
            get {
                return ResourceManager.GetString("MainPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager@niedzwiedzki.net.
        /// </summary>
        public static string ManagerEmail {
            get {
                return ResourceManager.GetString("ManagerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacz, jako &apos;wystawione&apos;.
        /// </summary>
        public static string MarkAsIssuedButton {
            get {
                return ResourceManager.GetString("MarkAsIssuedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy do faktury.
        /// </summary>
        public static string NameOfCompany {
            get {
                return ResourceManager.GetString("NameOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Nie dodałeś jeszcze ID księgowego do swojego profilu Dodaj ID księgowego, aby on również zobaczył fakturę!&gt;.
        /// </summary>
        public static string NoAccountantIdAdded {
            get {
                return ResourceManager.GetString("NoAccountantIdAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Nie dodałeś jeszcze nazwy swojej firmy do swojego profilu!&gt;.
        /// </summary>
        public static string NoCompanyNameAdded {
            get {
                return ResourceManager.GetString("NoCompanyNameAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła.
        /// </summary>
        public static string PasswordChange {
            get {
                return ResourceManager.GetString("PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetowanie hasła.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string ReadOperationName {
            get {
                return ResourceManager.GetString("ReadOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarejestruj.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZarejestrowaneLoginy.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejestracja.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectOperationName {
            get {
                return ResourceManager.GetString("RejectOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń {0} login ze swojego konta.
        /// </summary>
        public static string RemoveLoginFromYourAccount {
            get {
                return ResourceManager.GetString("RemoveLoginFromYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;ID żądania:&lt;/strong&gt; &lt;code&gt;{0}&lt;/code&gt;.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetuj.
        /// </summary>
        public static string ResetButton {
            get {
                return ResourceManager.GetString("ResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało zresetowane. Proszę &lt;a asp-page=&quot;./Login&quot;&gt;kliknąć tutaj&lt;/a&gt;, aby się zalogować..
        /// </summary>
        public static string ResetPasswordConfirmationText {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potwierdzenie zresetowania hasła.
        /// </summary>
        public static string ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zresetuj swoje hasło..
        /// </summary>
        public static string ResetPasswordText {
            get {
                return ResourceManager.GetString("ResetPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetowanie hasła.
        /// </summary>
        public static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zresetuj swoje hasło &lt;a href=&apos;{0}&apos;&gt;klikając tutaj&lt;/a&gt;..
        /// </summary>
        public static string ResetYourPasswordByClickingHere {
            get {
                return ResourceManager.GetString("ResetYourPasswordByClickingHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść filtrowanie i wróć do listy wszystkich faktur.
        /// </summary>
        public static string ReturnToViewAllButton {
            get {
                return ResourceManager.GetString("ReturnToViewAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapisz zmiany.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeedUserPW.
        /// </summary>
        public static string SeedUserPW {
            get {
                return ResourceManager.GetString("SeedUserPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje wylogowanie przebiegło pomyślnie..
        /// </summary>
        public static string SignedOutSuccessfulText {
            get {
                return ResourceManager.GetString("SignedOutSuccessfulText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylogowano.
        /// </summary>
        public static string SignedOutTitle {
            get {
                return ResourceManager.GetString("SignedOutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przełącz nawigację.
        /// </summary>
        public static string SwitchNavigation {
            get {
                return ResourceManager.GetString("SwitchNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwierzytelnianie dwuskładnikowe.
        /// </summary>
        public static string TwoFactorAuthentication {
            get {
                return ResourceManager.GetString("TwoFactorAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można załadować użytkownika z ID = {0}..
        /// </summary>
        public static string UnableToLoadUserWithId {
            get {
                return ResourceManager.GetString("UnableToLoadUserWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas wyłączania 2FA dla użytkownika o identyfikatorze &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedErrorWhenDisabling2FA {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhenDisabling2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas dodawania zewnętrznych danych logowania dla użytkownika o identyfikatorze &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedErrorWhileAddingExternalLogin {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileAddingExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas ładowania zewnętrznych danych logowania dla użytkownika o identyfikatorze &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedErrorWhileLoadingExternalLogin {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileLoadingExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił nieoczekiwany błąd podczas usuwania zewnętrznego logowania dla użytkownika o identyfikatorze &apos;{0}&apos;..
        /// </summary>
        public static string UnexpectedErrorWhileRemovingExternalLogin {
            get {
                return ResourceManager.GetString("UnexpectedErrorWhileRemovingExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateOperationName {
            get {
                return ResourceManager.GetString("UpdateOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaktualizuj hasło.
        /// </summary>
        public static string UpdateYourPassword {
            get {
                return ResourceManager.GetString("UpdateYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik zmienił swoje hasło..
        /// </summary>
        public static string UserChangedTheirPasswordSuccessfully {
            get {
                return ResourceManager.GetString("UserChangedTheirPasswordSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik utworzył nowe konto z hasłem..
        /// </summary>
        public static string UserCreatedNewAccountWithPassword {
            get {
                return ResourceManager.GetString("UserCreatedNewAccountWithPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o identyfikatorze &apos;{0}&apos; wyłączył 2fa..
        /// </summary>
        public static string UserDisabled2FA {
            get {
                return ResourceManager.GetString("UserDisabled2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o identyfikatorze &apos;{0}&apos; włączył 2FA z aplikacją uwierzytelniającą..
        /// </summary>
        public static string UserEnabled2FAWithAuth {
            get {
                return ResourceManager.GetString("UserEnabled2FAWithAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged out..
        /// </summary>
        public static string UserLoggedOut {
            get {
                return ResourceManager.GetString("UserLoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod weryfikacyjny.
        /// </summary>
        public static string VerificationCode {
            get {
                return ResourceManager.GetString("VerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kod weryfikacyjny jest nieprawidłowy..
        /// </summary>
        public static string VerificationCodeIsInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zweryfikuj.
        /// </summary>
        public static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witamy w naszym InvoiceManager! :) Tu będzie kiedyś super zajebista strona tytułowa. :D.
        /// </summary>
        public static string WelcomePageText {
            get {
                return ResourceManager.GetString("WelcomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Witaj, {0}!.
        /// </summary>
        public static string WelcomeUserText {
            get {
                return ResourceManager.GetString("WelcomeUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twoje hasło zostało zmienione..
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
    }
}
