//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InvoiceManager.Properties.ApplicationTexts", typeof(ApplicationTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID księgowego.
        /// </summary>
        public static string AccountantID {
            get {
                return ResourceManager.GetString("AccountantID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin@niedzwiedzki.net.
        /// </summary>
        public static string AdminEmail {
            get {
                return ResourceManager.GetString("AdminEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ApproveOperationName {
            get {
                return ResourceManager.GetString("ApproveOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateOperationName {
            get {
                return ResourceManager.GetString("CreateOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteOperationName {
            get {
                return ResourceManager.GetString("DeleteOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while seeding the database..
        /// </summary>
        public static string ErrorWhileSeedingTheDatabase {
            get {
                return ResourceManager.GetString("ErrorWhileSeedingTheDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wpisz nazwę firmy do faktury.
        /// </summary>
        public static string InsertNameOfCompanyErrorMessage {
            get {
                return ResourceManager.GetString("InsertNameOfCompanyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceAccountants.
        /// </summary>
        public static string InvoiceAccountantRole {
            get {
                return ResourceManager.GetString("InvoiceAccountantRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceAdministrators.
        /// </summary>
        public static string InvoiceAdministratorsRole {
            get {
                return ResourceManager.GetString("InvoiceAdministratorsRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manager@niedzwiedzki.net.
        /// </summary>
        public static string ManagerEmail {
            get {
                return ResourceManager.GetString("ManagerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa firmy do faktury.
        /// </summary>
        public static string NameOfCompany {
            get {
                return ResourceManager.GetString("NameOfCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string ReadOperationName {
            get {
                return ResourceManager.GetString("ReadOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string RejectOperationName {
            get {
                return ResourceManager.GetString("RejectOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SeedUserPW.
        /// </summary>
        public static string SeedUserPW {
            get {
                return ResourceManager.GetString("SeedUserPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateOperationName {
            get {
                return ResourceManager.GetString("UpdateOperationName", resourceCulture);
            }
        }
    }
}
